variable "network" {
  type    = string
  default = "network"
}
variable "ssh-key" {
  type    = string
  default = <<EOF
  Content of the ssh key
  generated by tls_key resource
  EOF
}

variable "private_key_path" {
  description = "privatekey_path"
  type        = string
  default     = "./linuxkey.pem"
}


variable "username" {
  type    = string
  default = "povadmin"
}