variable "network" {
  type    = string
  default = "network"
}
variable "ssh-key" {
  type    = string
  default = <<EOF
  Content of the ssh key
  generated by tls_key resource
  EOF
}
variable "username" {
  type    = string
  default = "povadmin"
}