variable "project" {
  type    = string
  default = "Project ID"
}

variable "region" {
  type    = string
  default = "Region"
}

variable "zone" {
  type    = string
  default = "Zone"
}


variable "gcp_OS" {
  type    = string
  default = "OS choice for all instances"
}

variable "gcp_instance_user" {
  type    = string
  default = "OS user for all instances"
}

variable "ssh-key" {
  type    = string
  default = <<EOF
  Content of the ssh key
  generated by tls_key resource
  EOF
}

variable "private_key_path" {
  description = "privatekey_path"
  type        = string
  default     = "./linuxkey.pem"
}

# Cribl Environment variables

variable "username" {
  type    = string
  default = "povadmin"
}

variable "cribl_pass" {
  type    = string
  default = "passtest"
}

variable "leader_count" {
  type    = number
  default = 1
}

variable "workers_count" {
  type    = number
  default = 1
}

variable "worker_size" {
  type    = string
  default = "e2-micro"
}

variable "worker_group" {
  type    = string
  default = "POV"
}

# Satellite Box variables

variable "satellite_box" {
  type        = bool
  default     = false
  description = "Deploy an instance to host all docker containers?"
}

variable "satellite_count" {
  type    = number
  default = 1
}

variable "satellite_box_size" {
  type    = string
  default = "t3.2xlarge"
}

variable "satellite_disk_size" {
  type    = number
  default = 65
}

# Satallite Box Docker containers variables

variable "splunk" {
  type        = bool
  default     = false
  description = "running a splunk instance for testing?"
}

variable "splunk_receiving_port" {
  type        = number
  default     = 9997
  description = "splunk receiving port"
}


variable "elk" {
  type        = bool
  default     = false
  description = "running ELK stack?"
}

variable "redis" {
  type        = bool
  default     = false
  description = "running Redis?"
}

variable "minio" {
  type        = bool
  default     = false
  description = "running Minio?"
}

variable "splunk_user" {
  type    = string
  default = "admin"
}

variable "splunk_passwd" {
  type    = string
  default = "passtest"
}

variable "elastic_user" {
  type    = string
  default = "elastic"
}

variable "elastic_passwd" {
  type    = string
  default = "passtest"
}

# Generic Varirables 

variable "syslog_port_tcp" {
  type    = number
  default = 9514
}

variable "syslog_port_udp" {
  type    = number
  default = 9514
}